export const totFields = [
  {
    name: "department",
    inputType: "select",
    url: "/Department",
    placeholder: "Select Department",
    label: "Department",
    required: true,
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "startOfWork",
    inputType: "datetime",
    // value: new Date(),
    placeholder: "Select Work",
    label: "Start of Work",
  },
  // {
  //   name: "permittingIssue",
  //   inputType: "select",
  //   options: [
  //     { value: 1, label: "Option 1" },
  //     { value: 2, label: "Option 2" },
  //   ],
  //   placeholder: "Select Issue",
  //   label: "Permitting Issue",
  //   zIndex: 1000,
  //   // zIndexInverse: 1000,
  // },
  {
    name: "contractor",
    inputType: "select",
    url: "/Contractor",
    placeholder: "Select Contractor",
    label: "Contractor",
    required: true,
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "shiftDelay",
    inputType: "select",
    url: "/ShiftDelay",
    placeholder: "Select Delay",
    label: "Shift Delays",
    required: true,
    zIndex: 999,
  },
  {
    name: "reworkDelay",
    inputType: "select",
    url: "/ReworkDelay",
    placeholder: "Select Delay",
    label: "Rework Delays",
    required: true,
    zIndex: 998,
  },
  {
    name: "delayReason",
    placeholder: "Enter Delay Reason",
    label: "Delay Reason",
    required: true,
    inputType: "textarea",
  },
  {
    name: "shift",
    inputType: "select",
    url: "/Shift",
    placeholder: "Select Shift",
    label: "Shift",
    required: true,
    zIndex: 997,
  },
  {
    name: "unit",
    inputType: "select",
    url: "/Unit",
    placeholder: "Select Unit",
    label: "Unit",
    required: true,
    zIndex: 996,
  },
  {
    name: "jobDescription",
    placeholder: "Enter Descriptions",
    label: "Descriptions",
    required: true,
    inputType: "textarea",
  },
  {
    name: "equipmentNo",
    placeholder: "Equipment#",
    label: "Equipment",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "twr",
    placeholder: "Enter TWR",
    label: "TWR - WO#",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "permitType",
    inputType: "select",
    url: "/PermitType",
    placeholder: "Select Permit Type",
    label: "Permit Type",
    required: true,
    zIndex: 995,
  },
  // {
  //   name: "company",
  //   inputType: "select",
  //   options: [
  //     { value: 1, label: "Option 1" },
  //     { value: 2, label: "Option 2" },
  //   ],
  //   placeholder: "Select Company",
  //   label: "Company",
  //   zIndex: 994,
  // },
  // {
  //   name: "timeRequested",
  //   inputType: "datetime",
  //   label: "Time Requested",
  //   placeholder: "Time Requested",
  //   value: new Date(),
  //   mode:"time"
  // },
  // {
  //   name: "timeSigned",
  //   inputType: "datetime",
  //   label: "Time Signed",
  //   placeholder: "Time Signed",
  //   value: new Date(),
  //   mode:"time"
  // },
  {
    name: "hoursDelayed",
    placeholder: "Enter Hours",
    label: "Hour(s) Delayed",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "manPower",
    placeholder: "Enter Man Power",
    label: "Man Power",
    keyboardType: "numeric",
  },
  {
    name: "manPowerAffected",
    placeholder: "Enter Affected Number",
    label: "Number of Man Power Affected",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "manHours",
    placeholder: "Enter Man Hours",
    label: "Man Hours",
    keyboardType: "numeric",
  },
  {
    name: "permittingIssue",
    inputType: "select",
    url: "/PermittingIssue",
    placeholder: "Select Issue",
    label: "Permitting Issue",
    required: true,
    zIndex: 993,
  }, 
  // {
  //   name: "foreman",
  //   inputType: "select",
  //   url: "/Account/getAllUsers?role=foreman",
  //   placeholder: "Select Foreman",
  //   labelAttributes: "userName",
  //   label: "Foreman",
  //   zIndex: 993,
  // }, 
  {
    name: "approver",
    inputType: "select",
    url: "/Account/getAllUsers?role=approver",
    placeholder: "Select Approver",
    labelAttributes: "userName",
    label: "Approver",
    zIndex: 993,
    required: true
  }, 
];
