export const totFields = [
  {
    name: "department",
    inputType: "select",
    url: "/Department",
    placeholder: "Select Department",
    label: "Department",
    required: true,
    zIndex: 3000,
  },
  {
    name: "unit",
    inputType: "select",
    url: "/Unit",
    placeholder: "Select Unit",
    label: "Unit",
    required: true,
    zIndex: 2999,
    condition: {
      fieldName: "department",
      action: "useValue",
      paramField: "Department.Id",
    },
    // wrapperStyle: { paddingBottom: 40 },
  },
  {
    name: "shift",
    inputType: "select",
    url: "/Shift",
    placeholder: "Select Shift",
    label: "Shift",
    required: true,
    zIndex: 1001,
  },
  {
    name: "startOfWork",
    inputType: "datetime",
    // value: new Date(),
    placeholder: "Select Work",
    label: "Start of Work",
  },
  {
    name: "reasonForRequest",
    inputType: "select",
    url: "/ReasonForRequest",
    placeholder: "Select Reason",
    label: "Request Reason",
    required: true,
    zIndex: 1000,
  },
  {
    name: "workScope",
    placeholder: "Enter Scope",
    label: "Work Scope",
  },
  {
    name: "delayDescription",
    placeholder: "Enter Delay Description",
    label: "Delay Description",
    // required: true,
    inputType: "textarea",
  },
  {
    name: "delayType",
    inputType: "select",
    url: "/DelayType",
    placeholder: "Select Delay",
    label: "Delay Type",
    required: true,
    zIndex: 997,
  },
  {
    name: "delayReason",
    inputType: "select",
    url: "/TOTLog/GetDelayReasons",
    placeholder: "Select Reason",
    label: "Delay Reason",
    // required: true,
    zIndex: 997,
    labelAttributes: "text",
    valueAttribute: "text",
    isEnum: true,
    wrapperStyle: { width: "48%", marginRight: 5 },
  },
  {
    name: "startOfWorkDelay",
    inputType: "select",
    url: "/StartOfWorkDelay",
    placeholder: "Select Start of Work",
    label: "Start of Work",
    // required: true,
    zIndex: 995,
    wrapperStyle: { width: "48%", marginRight: 5 },
    condition: {
      fieldName: "delayReason",
      action: "show",
      matchValue: "StartOfWork",
    },
  },
  {
    name: "shiftDelay",
    inputType: "select",
    url: "/ShiftDelay",
    placeholder: "Select Delay",
    label: "Shift Delays",
    // required: true,
    zIndex: 998,
    wrapperStyle: { width: "48%", marginRight: 5 },
    condition: {
      fieldName: "delayReason",
      action: "show",
      matchValue: "ShiftDelay",
    },
  },
  {
    name: "reworkDelay",
    inputType: "select",
    url: "/ReworkDelay",
    placeholder: "Select Delay",
    label: "Rework Delays",
    // required: true,
    zIndex: 996,
    wrapperStyle: { width: "48%", marginRight: 5 },
    condition: {
      fieldName: "delayReason",
      action: "show",
      matchValue: "ReworkDelay",
    },
  },
  {
    name: "permitType",
    inputType: "select",
    url: "/PermitType",
    placeholder: "Select Permit Type",
    label: "Permit Type",
    // required: true,
    zIndex: 995,
  },
  {
    name: "permitNo",
    placeholder: "Enter Permit",
    label: "Permit#",
    keyboardType: "numeric",
    maxLength: 5
  },
  // {
  //   name: "company",
  //   inputType: "select",
  //   url: "/Company",
  //   placeholder: "Select Company",
  //   label: "Company",
  //   required: true,
  //   zIndex: 986,
  // },
  {
    name: "foreman",
    placeholder: "Enter Foreman",
    label: "Foreman",
    // inputType: "select",
    // url: "/Account/getAllUsers?role=foreman",
    // labelAttributes: "userName",
    // zIndex: 996,
  },
  {
    name: "equipmentNo",
    placeholder: "Equipment#",
    label: "Equipment Number",
    required: true,
    // keyboardType: "numeric",
  },
  {
    name: "twr_label",
    label: "TWR #",
    inputType: "p",
    required: true,
    wrapperStyle: { marginBottom: -40, paddingTop: 25 },
  },
  {
    name: "twr_text",
    children: "TWR-",
    inputType: "p",
    wrapperStyle: { width: "12%", marginRight: 5 },
  },
  {
    name: "numericPart",
    inputType: "select",
    url: "/TOTLog/GetTWRNumericValues",
    placeholder: "Numeric",
    labelAttributes: "text",
    required: true,
    zIndex: 998,
    wrapperStyle: { width: "30%", marginRight: 5 },
  },
  {
    name: "alphabeticPart",
    inputType: "select",
    url: "/TOTLog/GetTWRAphabeticValues",
    placeholder: "Aphabetic",
    labelAttributes: "text",
    required: true,
    zIndex: 997,
    wrapperStyle: { width: "30%", marginRight: 5 },
  },
  {
    name: "twrText",
    placeholder: "TWR",
    required: true,
    keyboardType: "numeric",
    wrapperStyle: { width: "20%" },
  },
  // {
  //   name: "shiftDelay",
  //   inputType: "select",
  //   url: "/ShiftDelay",
  //   placeholder: "Select Delay",
  //   label: "Shift Delays",
  //   required: true,
  //   zIndex: 998,
  // },
  // {
  //   name: "delayReason",
  //   placeholder: "Enter Delay Reason",
  //   label: "Delay Reason",
  //   required: true,
  //   inputType: "textarea",
  // },

  // {
  //   name: "company",
  //   inputType: "select",
  //   options: [
  //     { value: 1, label: "Option 1" },
  //     { value: 2, label: "Option 2" },
  //   ],
  //   placeholder: "Select Company",
  //   label: "Company",
  //   zIndex: 994,
  // },
  // {
  //   name: "timeRequested",
  //   inputType: "datetime",
  //   label: "Time Requested",
  //   placeholder: "Time Requested",
  //   value: new Date(),
  //   mode:"time"
  // },
  // {
  //   name: "timeSigned",
  //   inputType: "datetime",
  //   label: "Time Signed",
  //   placeholder: "Time Signed",
  //   value: new Date(),
  //   mode:"time"
  // },
  // {
  //   name: "hoursDelayed",
  //   placeholder: "Enter Hours",
  //   label: "Hour(s) Delayed",
  //   required: true,
  //   keyboardType: "numeric",
  // },
  // {
  //   name: "manPower",
  //   placeholder: "Enter Man Power",
  //   label: "Man Power",
  //   keyboardType: "numeric",
  // },
  {
    name: "manPowerAffected",
    placeholder: "Enter Affected Number",
    label: "Total Head Count",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "manHours",
    placeholder: "Enter Man Hours",
    label: "Total Man Hours",
    keyboardType: "numeric",
    required: true,
  },
  // {
  //   name: "permittingIssue",
  //   inputType: "select",
  //   url: "/PermittingIssue",
  //   placeholder: "Select Issue",
  //   label: "Permitting Issue",
  //   required: true,
  //   zIndex: 993,
  // },
  // {
  //   name: "jobDescription",
  //   placeholder: "Enter Description",
  //   label: "Description",
  //   required: true,
  //   inputType: "textarea",
  // },
  // {
  //   name: "approver",
  //   inputType: "select",
  //   url: "/Approver",
  //   placeholder: "Select Approver",
  //   labelAttributes: "userName",
  //   label: "Approver",
  //   zIndex: 993,
  //   required: true,
  //   condition: {
  //     fieldName: "unit",
  //     action: "useValue",
  //     paramField: "Unit.Id",
  //   },
  // },
];
