export const wrrFields = [
  {
    name: "department",
    inputType: "select",
    url: "/Department",
    placeholder: "Select Department",
    label: "Department",
    required: true,
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "unit",
    inputType: "select",
    url: "/Unit",
    placeholder: "Select Unit",
    label: "Unit",
    required: true,
    zIndex: 2000,
  },
  {
    name: "calibrationDate",
    inputType: "datetime",
    placeholder: "Select Date",
    label: "Calibration Date",
  },
  {
    name: "fumeControlUsed",
    placeholder: "Enter Fume Control Used",
    label: "Fume Control Used",
    inputType: 'switch'
  },
  {
    name: "rodType",
    inputType: "select",
    url: '/RodType',
    placeholder: "Select Rod",
    label: "Welding Rod Type",
    required: true,
    zIndex: 998,
  },
  // {
  //   name: "contractor",
  //   inputType: "select",
  //   url: "/Contractor",
  //   placeholder: "Select Contractor",
  //   label: "Contractor",
  //   required: true,
  //   zIndex: 3000,
  //   zIndexInverse: 1000,
  // },
  // {
  //   name: "employee",
  //   inputType: "select",
  //   url: "/Employee",
  //   placeholder: "Select Employee",
  //   label: "Employee",
  //   zIndex: 3000,
  //   zIndexInverse: 1000,
  // },

  // {
  //   name: "twr",
  //   placeholder: "Enter TWR",
  //   label: "TWR - WO#",
  //   required: true,
  //   keyboardType: "numeric",
  // },
  {
    name: "twr_label",
    label: "TWR #",
    inputType: 'p',
    required: true,
    wrapperStyle: { marginBottom: -40, paddingTop: 25 },
  },
  {
    name: "twr_text",
    children: "TWR-",
    inputType: "p",
    wrapperStyle: { width: "12%", marginRight: 5 },
  },
  {
    name: "numericPart",
    inputType: "select",
    url: "/TOTLog/GetTWRNumericValues",
    placeholder: "Numeric",
    labelAttributes: "text",
    required: true,
    zIndex: 998,
    wrapperStyle: { width: "30%", marginRight: 5 },
  },
  {
    name: "alphabeticPart",
    inputType: "select",
    url: "/TOTLog/GetTWRAphabeticValues",
    placeholder: "Aphabetic",
    labelAttributes: "text",
    required: true,
    zIndex: 997,
    wrapperStyle: { width: "30%", marginRight: 5 },
  },
  {
    name: "twrText",
    placeholder: "TWR",
    required: true,
    keyboardType: "numeric",
    wrapperStyle: { width: "20%" },
  },
  {
    name: "weldMethod",
    inputType: "select",
    url: '/WeldMethod',
    placeholder: "Select Method",
    label: "Welding Method",
    required: true,
    zIndex: 997,
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter Email",
  },
  {
    name: "rodCheckedOut",
    inputType: "datetime",
    // value: new Date(),
    label: "Checkout Date",
    placeholder: "Enter Date",
  },
  {
    name: "location",
    label: "Location",
    required: true,
    placeholder: "Enter Location",
    inputType: "select",
    url: '/Location',
  },
  {
    name: "rodCheckedOutLbs",
    placeholder: "Enter Rod Checkout",
    label: "Rod Checked Out (lbs)",
    required: true,
    keyboardType: "numeric",
  },
  {
    name: "rodReturnedWasteLbs",
    placeholder: "Enter Rod Returned Waste",
    label: "Rod returned waste (lbs)",
    keyboardType: "numeric",
    required: true,
  },
  {
    name: "dateRodReturned",
    inputType: "datetime",
    placeholder: "Select Date",
    label: "Date of Rod Returned",
  },
  // {
  //   name: "approver",
  //   inputType: "select",
  //   url: "/Account/getAllUsers?role=approver",
  //   placeholder: "Select Approver",
  //   labelAttributes: "userName",
  //   label: "Approver",
  //   zIndex: 993,
  //   required: true
  // }, 
];
