export const wrrFields = [
  {
    name: "department",
    inputType: "select",
    url: "/Department",
    placeholder: "Select Department",
    label: "Department",
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "dateRodReturned",
    inputType: "datetime",
    placeholder: "Select Date",
    label: "Date of Rod Returned",
  },
  {
    name: "contractor",
    inputType: "select",
    url: "/Contractor",
    placeholder: "Select Contractor",
    label: "Contractor",
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "employee",
    inputType: "select",
    url: "/Employee",
    placeholder: "Select Employee",
    label: "Employee",
    zIndex: 3000,
    zIndexInverse: 1000,
  },
  {
    name: "unit",
    inputType: "select",
    url: "/Unit",
    placeholder: "Select Unit",
    label: "Unit",
    zIndex: 2000,
  },
  {
    name: "calibrationDate",
    inputType: "datetime",
    placeholder: "Select Date",
    label: "Calibration Date",
  },
  {
    name: "fumeControlUsed",
    placeholder: "Enter Fume Control Used",
    label: "Fume Control Used",
  },
  {
    name: "twr",
    placeholder: "Enter TWR",
    label: "TWR - WO#",
    keyboardType: "numeric",
  },
  {
    name: "rodType",
    inputType: "select",
    url: '/RodType',
    placeholder: "Select Rod",
    label: "Welding Rod Type",
    zIndex: 998,
  },
  {
    name: "weldMethod",
    inputType: "select",
    url: '/WeldMethod',
    placeholder: "Select Method",
    label: "Welding Method",
    zIndex: 997,
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter Email",
  },
  {
    name: "rodCheckedOut",
    inputType: "datetime",
    value: new Date(),
    label: "Checkout Date",
    placeholder: "Enter Date",
  },
  {
    name: "location",
    label: "Location",
    placeholder: "Enter Location",
    inputType: "select",
    url: '/Location',
  },
  {
    name: "rodCheckedOutLbs",
    placeholder: "Enter Rod Checkout",
    label: "Rod Checked Out (lbs)",
    keyboardType: "numeric",
  },
  {
    name: "rodReturnedWasteLbs",
    placeholder: "Enter Rod Returned Waste",
    label: "Rod returned waste (lbs)",
    keyboardType: "numeric",
  }
];
